'use client';
import { FormEvent, useState } from 'react';
const sectors=['1','2','3','4','5','6','7'];
const edu=['Elementary Level','Elementary Graduate','High School Level','High School Graduate','Vocational Graduate','College Level','College Graduate','Masters Level','Masters Graduate','Doctorate Level','Doctorate Graduate'];
export default function ProfilingForm(){
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<any>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch('/api/profile-submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Submission failed');setResult(j);window.scrollTo({top:0,behavior:'smooth'});}catch(x:any){setError(x.message||'Submission failed');}finally{setBusy(false)}}
 if(result) return <main className="profile-wrap"><section className="profile-card success-card"><img src="/logo.png" className="success-logo" alt="SK Nagsimbaanan"/><h2>Submission Received</h2><p>Your profile has been sent to SK Nagsimbaanan for verification.</p><div>Your reference number is:</div><div className="ref">{result.referenceNo}</div><p>{result.matchType==='existing'?'An existing YouthLink record was found. Your changes are pending verification.':'No exact existing record was found. Your registration is pending verification.'}</p><button onClick={()=>location.reload()}>Submit Another Profile</button></section></main>;
 return <><header className="profile-header"><div><img src="/logo.png" alt="SK Nagsimbaanan"/><h1>KK YOUTH PROFILING</h1><p>Office of the Sangguniang Kabataan • Barangay Nagsimbaanan, Bacnotan, La Union</p></div></header><main className="profile-wrap"><section className="profile-card intro"><h2>Katipunan ng Kabataan Profiling Form</h2><p>Please provide accurate and current information. Your submission will be checked against the existing YouthLink registry. Existing records will be submitted for verification before updating; new records will also require SK verification.</p><div className="privacy"><b>Data Privacy Notice:</b> Information submitted here will be used by SK Nagsimbaanan for lawful youth profiling, program planning, official communication, and related SK functions. Access is limited to authorized personnel.</div></section><form className="profile-card" onSubmit={submit}><div className="form-grid">
 <Field label="First Name *" name="first_name" required/><Field label="Middle Name" name="middle_name"/><Field label="Last Name *" name="last_name" required/><Field label="Suffix" name="suffix" placeholder="Jr., Sr., III"/>
 <Field label="Date of Birth *" name="birth_date" type="date" required/><Select label="Sector *" name="sector" required options={sectors}/><Select label="Sex Assigned at Birth *" name="sex_assigned_at_birth" required options={['Male','Female']}/><Select label="Civil Status *" name="civil_status" required options={['Single','Married','Widowed','Divorced','Separated','Annulled','Unknown','Live-in']}/>
 <Select label="Youth Classification *" name="youth_classification" required options={['ISY - In-School Youth','OSY - Out-of-School Youth','WY - Working Youth','YSN - Youth with Specific Needs']}/><Select label="Specific Needs Indicator" name="specific_needs_indicator" options={['Indigenous People','Children in Conflict with the Law','Person with Disability']}/>
 <Field label="Email Address" name="email" type="email"/><Field label="Contact Number *" name="contact_number" required pattern="09[0-9]{9}" maxLength={11} placeholder="09XXXXXXXXX"/><div className="full"><Field label="Complete Home Address *" name="home_address" required placeholder="House No./Street/Sector, Nagsimbaanan, Bacnotan, La Union"/></div>
 <Select label="Educational Attainment *" name="educational_attainment" required options={edu}/><Select label="Work Status *" name="work_status" required options={['Employed','Unemployed','Self-Employed','Currently looking for a job','Not interested looking for a job']}/><Select label="Registered SK Voter? *" name="registered_sk_voter" required options={['Yes','No']}/><Select label="Registered National Voter? *" name="registered_national_voter" required options={['Yes','No']}/><Select label="Voted in last SK election? *" name="voted_last_sk_election" required options={['Yes','No']}/><Select label="Attended a KK Assembly? *" name="attended_kk_assembly" required options={['Yes','No']}/><Select label="If yes, how many times?" name="kk_assembly_times" options={['1-2 Times','3-4 Times','5 and Above']}/><Select label="If no, why?" name="kk_assembly_no_reason" options={['There was no KK Assembly Meeting','Not Interested to attend']}/>
 <label className="consent full"><input type="checkbox" required/> <span>I certify that the information I provided is accurate and I consent to its processing for official KK/SK profiling and program administration purposes.</span></label><div className="full submit-row"><button disabled={busy}>{busy?'Submitting...':'Submit Profiling Form'}</button>{error&&<span className="error">{error}</span>}</div></div></form></main></>
}
function Field({label,...p}:any){return <label className="field"><span>{label}</span><input {...p}/></label>}
function Select({label,options,...p}:any){return <label className="field"><span>{label}</span><select {...p}><option value="">Select</option>{options.map((x:string)=><option key={x}>{x}</option>)}</select></label>}
